namespace: default
resources:
  - nginx.yaml
  - mysql.yaml
  - backend.yaml
configMapGenerator:
  - name: nginx
    files:
      - configs/default.conf
  - name: app
    files:
      - configs/application-prod.yml
      - configs/application.yml